-- MySQL Script generated by MySQL Workbench
-- 06/04/18 15:59:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema it482_fitts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema it482_fitts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `it482_fitts` DEFAULT CHARACTER SET utf8 ;
USE `it482_fitts` ;

-- -----------------------------------------------------
-- Table `it482_fitts`.`participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it482_fitts`.`participants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `age` INT NULL,
  `gender` VARCHAR(45) NULL,
  `handedness` TINYINT NULL,
  `arthritis` VARCHAR(45) NULL,
  `vision` VARCHAR(45) NULL,
  `avg_weekly_computer_usage` VARCHAR(45) NULL,
  `plays_fps_pc_games` TINYINT NULL,
  `mouse_or_trackpad_user` VARCHAR(45) NULL,
  `dpi_feeling` VARCHAR(45) NULL,
  `avg_weekly_exercise` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it482_fitts`.`blocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it482_fitts`.`blocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `participant_id` INT NOT NULL,
  `started_at` TIMESTAMP NULL,
  `finished_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blocks_participants_idx` (`participant_id` ASC),
  CONSTRAINT `fk_blocks_participants`
    FOREIGN KEY (`participant_id`)
    REFERENCES `it482_fitts`.`participants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it482_fitts`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it482_fitts`.`tasks` (
  `id` INT NOT NULL,
  `diameter` INT NULL,
  `distance` INT NULL,
  `direction` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it482_fitts`.`trials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it482_fitts`.`trials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `block_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `started_at` TIMESTAMP NULL,
  `finished_at` TIMESTAMP NULL,
  `distance_travelled` INT NULL,
  `errors` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trials_blocks1_idx` (`block_id` ASC),
  INDEX `fk_trials_tasks1_idx` (`task_id` ASC),
  CONSTRAINT `fk_trials_blocks1`
    FOREIGN KEY (`block_id`)
    REFERENCES `it482_fitts`.`blocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trials_tasks1`
    FOREIGN KEY (`task_id`)
    REFERENCES `it482_fitts`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
